version: '2'
services:
  web:
    build: .
    volumes:
      - .:/usr/app/
    ports:
      - "8080:8080"
    links:
      - mongodb:mongodb
  mongodb:
    image: mongo:jessie
    ports:
      - "27017:27017"
